export const GET_NEWS = "GET_NEWS";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAILED = "GET_NEWS_FAILED";

export const GET_NEWS_TOP_HEADLINES = "GET_NEWS_TOP_HEADLINES";
export const GET_NEWS_TOP_HEADLINES_SUCCESS = "GET_NEWS_TOP_HEADLINES_SUCCESS";
export const GET_NEWS_TOP_HEADLINES_FAILED = "GET_NEWS_TOP_HEADLINES_FAILED";

export const GET_ARTICLE = "GET_ARTICLE";